version: "3"
services:
  bnk-occlum-keyring:
    image: deepslabs/deeps-occlum-keyring:pre1.2.0
    restart: always
    network_mode: "host"
    environment:
        RUST_LOG: info
    volumes:
        - ./configs:/configs
        - ./data:/root/occlum_instance/data
        - ./configs/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf
    devices:
        - /dev/sgx/enclave:/dev/sgx/enclave
        - /dev/sgx/provision:/dev/sgx/provision
    command: bash -c 'cp /configs/keyring.toml /root/occlum_instance; source /root/.bashrc; cd /root/occlum_instance; occlum print mrsigner; occlum print mrenclave; occlum run /bin/deeps-keyring run /host/keyring.toml'

